### PR TITLE
Schedule - home work

### PR DESCRIPTION
**Pull request by PRZEMPM**

### CODE REVIEW

**Comment by PRZEMPM** [comment]
Wrzuciłem działający kod podstawowy, lecz bez realizacji bonusu, więc mam pomysły jak to zrobić, lecz nie chciałbym się angażować na razie w to. Prośba o wyłączenie testu bonusowego w _CmakeLists.txt_, gdyż gryzie się z podstawowym i zacznie działać ;)

**Comment by ziobron** [comment]
✅ CI Passed - Task: schedule
New user detected (@PRZEMPM).  Trying to automatically map accounts.

**Comment by ziobron** [comment]
✅ CI Passed - Task: schedule
🏅 Granted 12 XP for @PRZEMPM

**Comment by ziobron** [comment]
@PRZEMPM Your solution has not passed all checks (maybe it was only a formatting-check?) and you haven't modified this Pull Request during the last 7 days. It will be automatically closed after the next 7 days if it remains untouched.

**Comment by ziobron** [comment]
@PRZEMPM Your solution has not passed all checks (maybe it was only a formatting-check?) and you haven't modified this Pull Request during the last 7 days. It will be automatically closed after the next 7 days if it remains untouched.

**Comment by ziobron** [comment]
We are closing this PR. If you want to fix your code and get points, please re-open it or raise a new PR

**Pull request closed without merging**
