### PR TITLE
Update Catch2

### PR DESCRIPTION
**Pull request by arafalski**

### CODE REVIEW

**Review by ziobron — COMMENTED** [review]
Why this update is needed?

**Comment by ziobron** [comment]
And what is being changed? Is it a formatting change or bump to a newer version?

**Comment by ziobron** [comment]
If this is a formatting issue because clang-format fails, please add a new option to formatting-check job to exclude some directories and pass it here.

**Comment by arafalski** [comment]
Clang-format action already ignores catch2 files. It's just an update to the newest stable version of catch2 framework. I wasn't able to compile the old one.

**Comment by ziobron** [comment]
> Clang-format action already ignores catch2 files. It's just an update to the newest stable version of catch2 framework. I wasn't able to compile the old one.

Ok, so please put such information in the commit and PR description in future

**Comment by ziobron** [comment]
Your PR was merged!
🏅 2 XP granted. Thanks @anraf1001 for making course materials better!

**Pull request merged**
